# Generated by Django 4.2.7 on 2026-05-06 10:41

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания токена"
            ),
        ),
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="key",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="Ключ"
            ),
        ),
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirm_email_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь, связанный с этим токеном",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "unique": "Пользователь с таким именем уже существует."
                },
                help_text="Требуется 150 символов или меньше. Буквы, цифры и @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
