# Generated by Django 5.2.14 on 2026-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_confirmemailtoken_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь подтвердил свой email",
                verbose_name="Email подтверждён",
            ),
        ),
    ]
